export const routes = {
  signIn: "/mui-sign-in",
  dashboard: "/dashboard",
  assessment: "/assessment",
  strengths: "/strengths",
  setValues: "/set-values",
  myValues: "/my-values",
  sessions: "/sessions",
  newSession: "/new-session",
  editSession: "/session/:id",
  coaches: "/coaches",
  settings: "/settings",
  muiDefaultApp: "/mui-default-app",
  craDefaultApp: "/cra",
};
